apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 180
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: gont1er/django_app:latest
          env:
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_URL
          command: ["python", "manage.py", "migrate", "--noinput"]
     
